app/projects/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import Required, Length, Email, Regexp

class ProjectForm(Form):
    project_name = StringField('Project Name', validators=[Required()])
    submit = SubmitField('Submit')

app/projects/__init__.py
from flask import Blueprint
projects = Blueprint('projects', __name__)
from . import views

app/projects/views.py
from datetime import datetime
from flask import render_template, session, redirect, url_for, request, flash, abort
from flask_login import login_required, current_user
from . import projects
from .forms import ProjectForm
from .. import db
from ..models import User, Client, ProductArea, Feature, User, Project, Log

@projects.route('/new', methods=['GET', 'POST'])
@login_required
def create():
    """
    create a feature request
    """
    form = ProjectForm()
    if form.validate_on_submit():
        project = Project(project_name=form.project_name.data)
        try:
            db.session.add(project)
            db.session.commit()
            flash('You have successfully add the Project')
        except:
            flash('An error occured while trying to add the Project.')
        return redirect(url_for('.index'))
    return render_template('projects/create.html', form=form, name=session.get('name'),
                                    known=session.get('known', False),
                                    current_time=datetime.utcnow())

@projects.route('/index')
@login_required
def index():
    projects = Project.query.all()
    return render_template('projects/index.html', projects=projects, name=session.get('name'),
                                    known=session.get('known', False),
                                    current_time=datetime.utcnow())


@projects.route('/show/<id>')
@login_required
def show(id):
    project = Project.query.get_or_404(id)
    if project is None:
        abort(404)
    return render_template('projects/show.html', project=project, name=session.get('name'),
                                    known=session.get('known', False),
                                    current_time=datetime.utcnow())


@projects.route('/edit/<id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    project = Project.query.get_or_404(id)
    form = ProjectForm()
    if form.validate_on_submit():
        project.project_name=form.project_name.data
        try:
            db.session.add(project)
            db.session.commit()
            flash('You have successfully updated the Project')
        except:
            flash('An error occured while trying to update the project.')
        return redirect(url_for('.show', id=project.id))

    form.project_name.data = project.project_name
    return render_template('projects/edit.html', form=form, project=project)


@projects.route('/delete/', methods=['POST'])
@login_required
def delete():
    id = request.form['project_id']
    project = Project.query.get_or_404(id)
    try:
        db.session.delete(project)
        db.session.commit()
        flash('You have successfully deleted the project.')
    except:
        flash('An error occured while trying to delete the project.')
    return redirect(url_for('.index'))

@projects.context_processor
def inject_logs():
    """
    inject logs into all templates in projects
    """
    logs = Log.query.all()
    print "logs: ", logs
    return dict(logs=logs)

app/templates/projects/create.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
{{ super() }}

<div class="content-page">
    <!-- Start content -->
          <div class="content">
                <div class="container">

                  <!-- Page-Title -->
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="page-title-box">
                              <ol class="breadcrumb pull-right">
                                  <li><a href="#">Home</a></li>
                                  <li><a href="#">Project</a></li>
                                  <li class="active">Create</li>
                              </ol>
                              <h4 class="page-title">Projects</h4>
                          </div>
                      </div>
                  </div>

                        <div class="row">
                          <div class="col-sm-12">
                            <div class="card-box">
                              <h3>Create Project</h3>

                              <hr />
                            {{ utils.flashed_messages() }}
                            
                            {{ wtf.quick_form(form) }}
                            </div>
                          </div>

                        </div>
                </div>
        </div>
</div>

{% endblock %}

app/templates/projects/edit.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
{{ super() }}

<div class="content-page">
    <!-- Start content -->
          <div class="content">
                <div class="container">

                  <!-- Page-Title -->
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="page-title-box">
                              <ol class="breadcrumb pull-right">
                                  <li><a href="#">Home</a></li>
                                  <li><a href="#">Projects</a></li>
                                  <li class="active">Edit</li>
                              </ol>
                              <h4 class="page-title">Projects</h4>
                          </div>
                      </div>
                  </div>

                        <div class="row">
                          <div class="col-sm-12">
                            <div class="card-box">
                              <h3>Edit Project ({{project.id}})</h3>

                              <hr />
                            {{ utils.flashed_messages() }}
                            
                            {{ wtf.quick_form(form) }}
                            </div>
                          </div>

                        </div>
                </div>
        </div>
</div>

{% endblock %}

app/templates/projects/index.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}

{% block page_content %}
{{ super() }}

  <!-- ============================================================== -->
  <!-- Start right Content here -->
  <!-- ============================================================== -->

  <div class="content-page">
      <!-- Start content -->
            <div class="content">
                <div class="container">

                    <!-- Page-Title -->
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="page-title-box">

                                <ol class="breadcrumb pull-right">
                                    <li><a href="#">Home</a></li>
                                    <li><a href="#">Projects</a></li>
                                    <li class="active">Manage</li>
                                </ol>

                                <h4 class="page-title">Projects</h4>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-12">
                          <div class="card-box">

                            <h3>Manage Projects</h3>

                            <hr />

                              {{ utils.flashed_messages() }}

                            <div class="table-rep-plugin">
                              <div class="table-responsive" data-pattern="priority-columns">
                                <table id="tech-companies-1" class="table  table-striped">
                                  <thead>
                                    <tr>
                                      <th data-priority="1">SN</th>
                                      <th data-priority="2">Project Name</th>
                                    </tr>
                                  </thead>
                                  <tbody>

                                    {% set count = 1 %}
                                    {% for project in projects %}
                                    <tr>
                                        <th><span class="co-name">{{count}}</span></th>
                                        <td>{{ project.project_name }}</td>
                                        <td>
                                              <a href="#" class="mr-3" data-toggle="modal" data-target="#exampleModal" data-id="{{project.id}}" data-project_name="{{project.project_name}}">
                                                      <i class="md md-delete"></i> Delete
                                              </a>
                                              &nbsp;
                                              <a href="{{ url_for('projects.show', id=project.id) }}"><i class="ti-eye"></i> View</a>
                                        </td>
                                    </tr>
                                    {% set count = count + 1 %}
                                    {% endfor %}


                                  </tbody>
                                </table>
                              </div>

                            </div>

                          </div>
                        </div>
                    </div>
                    <!-- end row -->


                </div>
                <!-- end container -->

            </div>
      <!-- end content -->
  </div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header" id="difftype">
              <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
              </div>
              <form action="{{ url_for('projects.delete')}}" method="post">
              <div class="modal-body">
                  <div class="row text-center">
                      <img src="{{ url_for('static', filename = 'images/delete.png') }}" />
                  </div>
              </div>

                  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                  <input type="hidden" id="project_id" name="project_id">
                  <p class="text-center">Are you sure you want to delete this client </p>
                  <p  class="text-center">Initiated for <span id="project_name"></span></p>

                  <div class="modal-footer">
                      <button type="button" class="btn btncan" data-dismiss="modal">DON'T DELETE</button>
                      <button type="submit" class="btn btn-danger">DELETE</button>
                  </div>

              </form>
          </div>
      </div>
  </div>
  <!-- ============================================================== -->
  <!-- End Right content here -->
  <!-- ============================================================== -->


{% endblock %}

{% block script %}
<script>

  $(function() {
      $('#exampleModal').on("show.bs.modal", function (e) {
          $("#project_id").val($(e.relatedTarget).data('id'));
          $("#project_name").text($(e.relatedTarget).data('project_name'));
      });
  });

</script>
{% endblock %}

app/templates/projects/show.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
{{ super() }}

<div class="content-page">
    <!-- Start content -->
          <div class="content">
                <div class="container">

                  <!-- Page-Title -->
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="page-title-box">
                              <ol class="breadcrumb pull-right">
                                  <li><a href="#">Home</a></li>
                                  <li><a href="#">Projects</a></li>
                                  <li class="active">Create New</li>
                              </ol>
                              <h4 class="page-title">Projects</h4>
                          </div>
                      </div>
                  </div>

                        <div class="row">
                          <div class="col-sm-12">
                            <div class="card-box">
                              <h3>Show Project ({{ project.id }})</h3>

                              <hr />

                              {{ utils.flashed_messages() }}

                              <div class="container wrapper mb-5">
                                      <div class="container">
                                          <div class="card">
                                              <div class="card-body p-0">
                                                  <table class="table table-hover">
                                                      <tbody>
                                                          <tr style="padding-top:20px;">
                                                              <th scope="row">Project Name</th>
                                                              <td>{{ project.project_name }}</td>
                                                          </tr>
                                                          <tr>
                                                              <th scope="row">&nbsp;</th>
                                                              <td>
                                                                  <button class="btn btn-primary generate" onclick="location.href='{{ url_for('projects.edit', id=project.id) }}';">EDIT</button>
                                                                  <button class="btn btn-danger generate" data-toggle="modal" data-target="#exampleModal" data-id="{{project.id}}" data-project_name="{{project.project_name}}">DELETE</button>
                                                              </td>
                                                          </tr>
                                                      </tbody>
                                                  </table>
                                              </div>

                                          </div>

                                      </div>
                                  </div>



                            </div>
                          </div>

                        </div>
                </div>
        </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="difftype">
            <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <form action="{{ url_for('projects.delete')}}" method="post">
            <div class="modal-body">
                <div class="row text-center">
                    <img src="{{ url_for('static', filename = 'images/delete.png') }}" />
                </div>
            </div>

                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <input type="hidden" id="project_id" name="project_id">
                <p class="text-center">Are you sure you want to delete this client </p>
                <p  class="text-center">Initiated for <span id="project_name"></span></p>

                <div class="modal-footer">
                    <button type="button" class="btn btncan" data-dismiss="modal">DON'T DELETE</button>
                    <button type="submit" class="btn btn-danger">DELETE</button>
                </div>

            </form>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- End Right content here -->
<!-- ============================================================== -->


{% endblock %}

{% block script %}
<script>

$(function() {
    $('#exampleModal').on("show.bs.modal", function (e) {
        $("#project_id").val($(e.relatedTarget).data('id'));
        $("#project_name").text($(e.relatedTarget).data('project_name'));
    });
});

</script>
{% endblock %}