app/hrequests/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField, SelectField, DateField, TextAreaField, IntegerField
from wtforms.widgets import HiddenInput
from wtforms.validators import Required, Length, Email, Regexp
from ..models import Feature, User, Client, ProductArea, Project
from wtf_tinymce.forms.fields import TinyMceField

class FeatureForm(Form):
    title = StringField('Title', validators=[Required()])
    description = TextAreaField('Description', validators=[Required()])
    client_priority = SelectField('Client Priority', validators=[Required()],coerce=int, default=None)
    target_date = DateField('Target Date', format="%m/%d/%Y", validators=[Required()])
    product_area = SelectField('Product Area', coerce=int, validators=[Required()], default=None)
    user =  IntegerField("", widget=HiddenInput() )
    client = SelectField('Client', coerce=int, validators=[Required()], default=(None, '--'))
    project = SelectField('Project', coerce=int, validators=[Required()], default=None)
    submit = SubmitField('Submit')

    def __init__(self, *args, **kwargs):
        super(FeatureForm, self).__init__(*args, **kwargs)
        self.client.choices = [(0, 'Please Select')] + [(client.id, client.client_name) for client in Client.query.order_by(Client.client_name).all()]
        self.project.choices = [(0, 'Please Select')] + [(project.id, project.project_name) for project in Project.query.order_by(Project.project_name).all()]
        self.product_area.choices = [(0, 'Please Select')] + [(pa.id, pa.product_area) for pa in ProductArea.query.order_by(ProductArea.product_area).all()]
        self.client_priority.choices = get_client_priority()
        #[('', 'Please Select'), ('1', 'low'), ('2', 'medium'), ('3', 'High')]

def get_client_priority():
    choices = [ (x, x) for x in range(1, Feature.query.count() + 1) ]
    if len(choices) < 1:
        choices = [ (1,1) ]
    return [(0, 'Please Select')] + choices

app/hrequests/__init__.py
from flask import Blueprint
hrequests = Blueprint('hrequests', __name__)
from . import views

app/hrequests/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from datetime import datetime
from flask import render_template, session, redirect, url_for, request, \
    flash, current_app, abort
from flask_login import login_required, current_user
from . import hrequests
from forms import FeatureForm
from .. import db
from ..models import User, Client, ProductArea, Feature, User, Log

import app


@hrequests.route('/new', methods=['GET', 'POST'])
@login_required
def create():
    """
    create a feature request
    """
    form = FeatureForm()
    if form.validate_on_submit():

        feature = Feature(
            title=form.title.data,
            description=form.description.data,
            client_priority=form.client_priority.data,
            target_date=form.target_date.data,
            product_area_id=form.product_area.data,
            client_id=form.client.data,
            project_id=form.project.data,
            user_id=current_user._get_current_object().id,
            )

        # reorder
        arr = \
            Feature.query.filter(Feature.project_id == feature.project_id) \
                         .filter(Feature.client_id == form.client.data) \
                         .order_by(Feature.client_priority).all()
        reorder(arr, form.client_priority.data)
        try:
            db.session.add(feature)
            db.session.commit()
            log = Log(
                    username=current_user._get_current_object().username,
                    feature=feature,
                    action="created",
                    timestamp=datetime.utcnow()
                )
            db.session.add(log)
            db.session.commit()
            flash('You have successfully created the Feature Request.')
        except:
            flash('Error: failed to create the Feature Request.')

        return redirect(url_for('.index'))
    form.user.data = current_user._get_current_object().id
    return render_template('hrequests/create.html', form=form)


@hrequests.route('/index')
@login_required
def index():
    """
    list all feature requests
    """
    page = request.args.get('page', 1, type=int)

    pagination = \
        Feature.query.order_by(Feature.timestamp.desc()).paginate(page,
            current_app.config['POSTS_PER_PAGE'], False)

    features = pagination.items

    return render_template('hrequests/index.html', features=features,
                           pagination=pagination)


@hrequests.route('/show/<id>')
@login_required
def show(id):

    feature = Feature.query.get_or_404(id)
    if feature is None:
        abort(404)
    return render_template('hrequests/show.html', feature=feature,
                           name=session.get('name'),
                           known=session.get('known', False),
                           current_time=datetime.utcnow())


@hrequests.route('/edit/<id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    """
    edit a feature request
    """
    feature = Feature.query.get_or_404(id)

    form = FeatureForm()

    if form.validate_on_submit():

        feature.title = form.title.data
        feature.description = form.description.data
        feature.client_priority = form.client_priority.data
        feature.target_date = datetime.utcnow()
        feature.product_area_id = form.product_area.data
        feature.client_id = form.client.data
        feature.project_id = form.project.data
        feature.user_id = current_user._get_current_object().id
        arr = Feature.query.filter(Feature.client_id == form.client.data) \
                            .filter(Feature.project_id == feature.project_id) \
                            .filter(Feature.id != feature.id) \
                            .order_by(Feature.client_priority).all()
        reorder(arr, form.client_priority.data)
        try:
            db.session.add(feature)
            db.session.commit()
            log = Log(
                    username=current_user._get_current_object().username,
                    feature=feature,
                    action="updated",
                    timestamp=datetime.utcnow()
            )

            db.session.add(log)
            flash('You have successfully updated the Feature Request.')
        except:
            flash('An error occured while trying to update the Feature Request.')

        return redirect(url_for('.show', id=feature.id))

    form.title.data = feature.title
    form.description.data = feature.description
    form.client_priority.data = feature.client_priority
    form.target_date.data = feature.target_date
    form.product_area.data = feature.product_area_id
    form.client.data = feature.client_id
    form.project.data = feature.project_id
    form.user.data = current_user._get_current_object().id

    return render_template('hrequests/edit.html', form=form,
                           feature=feature)


@hrequests.route('/delete/', methods=['POST'])
@login_required
def delete():
    """
    delete a feature request
    """
    id = request.form['request_id']
    feature = Feature.query.get_or_404(id)
    try:
        db.session.delete(feature)

        log = Log(
                username=current_user._get_current_object().username,
                feature=feature,
                action="deleted",
                timestamp=datetime.utcnow()
            )

        db.session.add(log)
        db.session.commit()
        flash('You have successfully deleted the Feature Request.')
    except:
        flash('An error occured while deleting a Feature Request.')

    return redirect(url_for('.index'))

@hrequests.context_processor
def inject_logs():
    """
    inject logs into all templates in hrequests
    """
    logs = Log.query.all()
    print "logs: ", logs
    return dict(logs=logs)


def reorder(arr, index):

    i = len(arr)

    while i >= index:
        arr[i - 1].client_priority = i + 1
        db.session.add(arr[i - 1])
        i = i - 1

    while i > 0:
        arr[i - 1].client_priority = i
        db.session.add(arr[i - 1])
        i = i - 1
    db.session.commit()

app/templates/hrequests/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/hrequests/create.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
{% import 'wtf_tinymce/editor.html' as tinymce with context %}
{{ super() }}

<div class="content-page">
    <!-- Start content -->
          <div class="content">
                <div class="container">

                  <!-- Page-Title -->
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="page-title-box">
                              <ol class="breadcrumb pull-right">
                                  <li><a href="#">Home</a></li>
                                  <li><a href="#">Features</a></li>
                                  <li class="active">Create New</li>
                              </ol>
                              <h4 class="page-title">Feature Requests</h4>
                          </div>
                      </div>
                  </div>

                        <div class="row">
                          <div class="col-sm-12">
                            <div class="card-box">
                              <h3>Create New Feature Requests</h3>

                              <hr />

                              {{ utils.flashed_messages() }}

                            {{ wtf.quick_form(form) }}
                            </div>
                          </div>

                        </div>
                </div>
        </div>
</div>

{% endblock %}

{% block script %}
  <script src="{{ url_for('static', filename = 'plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' ) }}">

  </script>
  <script>
      $(function() {
        $( "#target_date" ).datepicker();
      });
  </script>
{% endblock %}

app/templates/hrequests/edit.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% import 'wtf_tinymce/editor.html' as tinymce with context %}
{% block page_content %}
{{ super() }}

<div class="content-page">
    <!-- Start content -->
          <div class="content">
                <div class="container">

                  <!-- Page-Title -->
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="page-title-box">
                              <ol class="breadcrumb pull-right">
                                  <li><a href="#">Home</a></li>
                                  <li><a href="#">Features</a></li>
                                  <li class="active">Edit</li>
                              </ol>
                              <h4 class="page-title">Feature Requests</h4>
                          </div>
                      </div>
                  </div>

                        <div class="row">
                          <div class="col-sm-12">
                            <div class="card-box">
                              <h3>Edit Feature Requests ({{feature.id}})</h3>

                              <hr />

                            {{ utils.flashed_messages() }}

                            {{ wtf.quick_form(form) }}
                            </div>
                          </div>

                        </div>
                </div>
        </div>
</div>

{% endblock %}
{% block script %}
  <script src="{{ url_for('static', filename = 'plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' ) }}">

  </script>
  <script>
      $(function() {
        $( "#target_date" ).datepicker();
      });
  </script>
{% endblock %}

app/templates/hrequests/index.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}
{% import "hrequests/_macros.html" as macros %}

{% block page_content %}
{{ super() }}

  <!-- ============================================================== -->
  <!-- Start right Content here -->
  <!-- ============================================================== -->

  <div class="content-page">
      <!-- Start content -->
            <div class="content">
                <div class="container">

                    <!-- Page-Title -->
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="page-title-box">

                                <ol class="breadcrumb pull-right">
                                    <li><a href="#">Home</a></li>
                                    <li><a href="#">Features</a></li>
                                    <li class="active">Manage</li>
                                </ol>

                                <h4 class="page-title">Feature Requests</h4>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-12">
                          <div class="card-box">

                            <h3>Manage Feature Requests</h3>

                            <hr />

                            {{ utils.flashed_messages() }}

                            <div class="table-rep-plugin">
                              <div class="table-responsive" data-pattern="priority-columns">



                                <table id="tech-companies-1" class="table  table-striped">
                                  <thead>
                                    <tr>
                                      <th data-priority="1">SN</th>
                                      <th data-priority="2">Title</th>
                                      <th data-priority="4">Client Priority</th>
                                      <th data-priority="9">Target Date</th>
                                      <th data-priority="6">Product Areas</th>
                                      <th data-priority="8">Client</th>
                                      <th data-priority="9">Project</th>
                                      <th data-priority="9">Actions</th>
                                    </tr>
                                  </thead>
                                  <tbody>

                                    {% set count = 1 %}
                                    {% for feature in features %}
                                    <tr>
                                        <th><span class="co-name">{{ count }}</span></th>
                                        <td>{{ feature.title }}</td>
                                        <td>{{ feature.client_priority }}</td>
                                        <td>{{ feature.target_date }}</td>
                                        <td>{{ feature.product_area.product_area }}</td>
                                        <td>{{ feature.client.client_name }}</td>
                                        <td>{{ feature.project.project_name }}</td>
                                        <td>
                                              <a href="#" class="mr-3" data-toggle="modal" data-target="#exampleModal" data-id="{{feature.id}}" data-request_title="{{feature.title}}">
                                                      <i class="md md-delete"></i> Delete
                                              </a>
                                              &nbsp;
                                              <a href="{{ url_for('hrequests.show', id=feature.id) }}"><i class="ti-eye"></i> View</a>
                                        </td>
                                    </tr>
                                    {% set count = count + 1 %}
                                    {% endfor %}


                                  </tbody>
                                </table>
                              </div>

                            </div>

                          </div>
                        </div>
                    </div>

                    {% if pagination %}
                    <div class="pagination">
                        {{ macros.pagination_widget(pagination, '.index') }}
                    </div>
                    {% endif %}
                    

                    <!-- end row -->


                </div>
                <!-- end container -->

            </div>
      <!-- end content -->
  </div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header" id="difftype">
              <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
              </div>
              <div class="modal-body">
                  <div class="row text-center">
                      <img src="{{ url_for('static', filename = 'images/delete.png') }}" />
                  </div>
              </div>
              <form action="{{ url_for('hrequests.delete')}}" method="post">
                     <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                     <input type="hidden" id="request_id" name="request_id">
                    <p class="text-center">Are you sure you want to delete this request </p>
                    <p  class="text-center">Initiated for <span id="request_title"></span></p>
                    <div class="modal-footer">
                        <button type="button" class="btn btncan" data-dismiss="modal">DON'T DELETE</button>
                        <button type="submit" class="btn btn-danger">DELETE</button>
                    </div>
              </form>
          </div>
      </div>
  </div>
  <!-- ============================================================== -->
  <!-- End Right content here -->
  <!-- ============================================================== -->


{% endblock %}

{% block script %}
<script>
	$(document).ready(function() {
        $('.request').addClass("active");
  });

    $(function() {
        $('#exampleModal').on("show.bs.modal", function (e) {
            $("#request_id").val($(e.relatedTarget).data('id'));
            $("#request_title").text($(e.relatedTarget).data('request_title'));
        });
    });


    $('.datefade').datepicker({
      	format: "yyyy-mm-dd",
      	autoclose: true,
      	todayHighlight: true,
        orientation: "bottom"
    });

    var today = new Date();
    $('#demoDate').datepicker({
        format: "yyyy-mm-dd",
        autoclose: true,
        todayHighlight: true,
        orientation: "bottom",
        endDate: "today",
        maxDate: today
    });
</script>
{% endblock %}

app/templates/hrequests/show.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
{{ super() }}

<div class="content-page">
    <!-- Start content -->
          <div class="content">
                <div class="container">

                  <!-- Page-Title -->
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="page-title-box">
                              <ol class="breadcrumb pull-right">
                                  <li><a href="#">Home</a></li>
                                  <li><a href="#">Features</a></li>
                                  <li class="active">Create New</li>
                              </ol>
                              <h4 class="page-title">Feature Requests</h4>
                          </div>
                      </div>
                  </div>

                        <div class="row">
                          <div class="col-sm-12">
                            <div class="card-box">
                              <h3>Show Feature Request ({{ feature.id }})</h3>

                              <hr />

                              {{ utils.flashed_messages() }}

                              <div class="container wrapper mb-5">
                                      <div class="container">
                                          <div class="card">
                                              <div class="card-body p-0">
                                                  <table class="table table-hover">
                                                      <tbody>
                                                          <tr style="padding-top:20px;">
                                                              <th scope="row">Title</th>
                                                              <td>{{ feature.title }}</td>

                                                          </tr>
                                                          <tr>
                                                              <th scope="row">Description</th>
                                                              <td>{{ feature.description }}</td>

                                                          </tr>
                                                          <tr>
                                                              <th scope="row">Client Priority</th>
                                                              <td>{{ feature.client_priority }}</td>

                                                          </tr>
                                                          <tr>
                                                              <th scope="row">Product Area</th>
                                                              <td>{{ feature.product_area.product_area }}</td>

                                                          </tr>
                                                          <tr>
                                                              <th scope="row">User</th>
                                                              <td>{{ feature.user.username }}</td>
                                                          </tr>
                                                          <tr>
                                                              <th scope="row">Client</th>
                                                              <td>{{ feature.client.client_name }}</td>
                                                          </tr>
                                                          <tr>
                                                              <th scope="row">Project Name</th>
                                                              <td>{{ feature.project.project_name }}</td>
                                                          </tr>
                                                          <tr>
                                                              <th scope="row">&nbsp;</th>
                                                              <td>
                                                                  <button class="btn btn-primary generate" onclick="location.href='{{ url_for('hrequests.edit', id=feature.id) }}';">EDIT</button>
                                                                  <button class="btn btn-danger generate" data-toggle="modal" data-target="#exampleModal" data-id="{{feature.id}}" data-request_title="{{feature.title}}">DELETE</button>
                                                              </td>
                                                          </tr>
                                                      </tbody>
                                                  </table>
                                              </div>

                                          </div>

                                      </div>
                                  </div>



                            </div>
                          </div>

                        </div>
                </div>
        </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="difftype">
            <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <div class="row text-center">
                    <img src="{{ url_for('static', filename = 'images/delete.png') }}" />
                </div>
            </div>
            <form action="{{ url_for('hrequests.delete')}}" method="post">
                   <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                   <input type="hidden" id="request_id" name="request_id">
                  <p class="text-center">Are you sure you want to delete this request </p>
                  <p  class="text-center">Initiated for <span id="request_title"></span></p>
                  <div class="modal-footer">
                      <button type="button" class="btn btncan" data-dismiss="modal">DON'T DELETE</button>
                      <button type="submit" class="btn btn-danger">DELETE</button>
                  </div>
            </form>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- End Right content here -->
<!-- ============================================================== -->


{% endblock %}

{% block script %}
<script>

  $(function() {
      $('#exampleModal').on("show.bs.modal", function (e) {
          $("#request_id").val($(e.relatedTarget).data('id'));
          $("#request_title").text($(e.relatedTarget).data('request_title'));
      });
  });

</script>
{% endblock %}