app/productareas/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import Required, Length, Email, Regexp

class ProductAreaForm(Form):
    product_area = StringField('Product Area', validators=[Required()])
    submit = SubmitField('Submit')

app/productareas/__init__.py
from flask import Blueprint
productareas = Blueprint('productareas', __name__)
from . import views

app/productareas/views.py
from datetime import datetime
from flask import render_template, session, redirect, url_for, request, flash, abort
from flask_login import login_required, current_user
from . import productareas
from .forms import ProductAreaForm
from .. import db
from ..models import User, Client, ProductArea, Feature, User, Log

@productareas.route('/new', methods=['GET', 'POST'])
@login_required
def create():
    form = ProductAreaForm()
    if form.validate_on_submit():
        product_area = ProductArea(product_area=form.product_area.data)
        try:
            db.session.add(product_area)
            db.session.commit()
            flash('You have successfully add the Product Area.')
        except:
            flash('An error occured while trying to add the Product Area.')
        return redirect(url_for('.index'))

    return render_template('productareas/create.html', form=form, name=session.get('name'),
                                    known=session.get('known', False),
                                    current_time=datetime.utcnow())

@productareas.route('/index')
@login_required
def index():
    product_areas = ProductArea.query.all()
    return render_template('productareas/index.html', product_areas=product_areas, name=session.get('name'),
                                    known=session.get('known', False),
                                    current_time=datetime.utcnow())


@productareas.route('/show/<id>')
@login_required
def show(id):
    product_area = ProductArea.query.get_or_404(id)
    if product_area is None:
        abort(404)
    return render_template('productareas/show.html', product_area=product_area, name=session.get('name'),
                                    known=session.get('known', False),
                                    current_time=datetime.utcnow())


@productareas.route('/edit/<id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    product_area = ProductArea.query.get_or_404(id)
    form = ProductAreaForm()
    if form.validate_on_submit():
        product_area.product_area=form.product_area.data
        try:
            db.session.add(product_area)
            db.session.commit()
            flash('You have successfully updated the Product Area.')
        except:
            flash('An error occured while trying to update the Product Area.')
        return redirect(url_for('.show', id=product_area.id))

    form.product_area.data = product_area.product_area
    return render_template('productareas/edit.html', form=form, product_area=product_area)


@productareas.route('/delete/', methods=['POST'])
@login_required
def delete():
    id = request.form['product_area_id']
    product_area = ProductArea.query.get_or_404(id)
    try:
        db.session.delete(product_area)
        db.session.commit()
        flash('You have successfully deleted the Product Area.')
    except:
        flash('An error occured while trying to delete the Product Area.')
    return redirect(url_for('.index'))

@productareas.context_processor
def inject_logs():
    """
    inject logs into all templates in product areas
    """
    logs = Log.query.all()
    print "logs: ", logs
    return dict(logs=logs)

app/templates/productareas/create.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
{{ super() }}

<div class="content-page">
    <!-- Start content -->
          <div class="content">
                <div class="container">

                  <!-- Page-Title -->
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="page-title-box">
                              <ol class="breadcrumb pull-right">
                                  <li><a href="#">Home</a></li>
                                  <li><a href="#">Product Areas</a></li>
                                  <li class="active">Create</li>
                              </ol>
                              <h4 class="page-title">Product Areas</h4>
                          </div>
                      </div>
                  </div>

                        <div class="row">
                          <div class="col-sm-12">
                            <div class="card-box">
                              <h3>Create Product Area</h3>

                              <hr />
                            {{ utils.flashed_messages() }}

                            {{ wtf.quick_form(form) }}
                            </div>
                          </div>

                        </div>
                </div>
        </div>
</div>

{% endblock %}

app/templates/productareas/edit.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
{{ super() }}

<div class="content-page">
    <!-- Start content -->
          <div class="content">
                <div class="container">

                  <!-- Page-Title -->
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="page-title-box">
                              <ol class="breadcrumb pull-right">
                                  <li><a href="#">Home</a></li>
                                  <li><a href="#">Product Areas</a></li>
                                  <li class="active">Edit</li>
                              </ol>
                              <h4 class="page-title">Product Areas</h4>
                          </div>
                      </div>
                  </div>

                        <div class="row">
                          <div class="col-sm-12">
                            <div class="card-box">
                              <h3>Edit Product Areas ({{product_area.id}})</h3>

                              <hr />
                            {{ utils.flashed_messages() }}
                            
                            {{ wtf.quick_form(form) }}
                            </div>
                          </div>

                        </div>
                </div>
        </div>
</div>

{% endblock %}

app/templates/productareas/index.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}

{% block page_content %}
{{ super() }}

  <!-- ============================================================== -->
  <!-- Start right Content here -->
  <!-- ============================================================== -->

  <div class="content-page">
      <!-- Start content -->
            <div class="content">
                <div class="container">

                    <!-- Page-Title -->
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="page-title-box">

                                <ol class="breadcrumb pull-right">
                                    <li><a href="#">Home</a></li>
                                    <li><a href="#">Product Areas</a></li>
                                    <li class="active">Manage</li>
                                </ol>

                                <h4 class="page-title">Product Areas</h4>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-12">
                          <div class="card-box">

                            <h3>Manage Product Areas</h3>

                            <hr />

                            {{ utils.flashed_messages() }}

                            <div class="table-rep-plugin">
                              <div class="table-responsive" data-pattern="priority-columns">
                                <table id="tech-companies-1" class="table  table-striped">
                                  <thead>
                                    <tr>
                                      <th data-priority="1">SN</th>
                                      <th data-priority="2">Product Areas</th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    {% set count = 1 %}
                                    {% for product_area in product_areas %}
                                    <tr>
                                        <th><span class="co-name">{{count}}</span></th>
                                        <td>{{ product_area.product_area }}</td>
                                        <td>
                                              <a href="#" class="mr-3" data-toggle="modal" data-target="#exampleModal" data-id="{{product_area.id}}" data-product_area="{{product_area.product_area}}">
                                                      <i class="md md-delete"></i> Delete
                                              </a>
                                              &nbsp;
                                              <a href="{{ url_for('productareas.show', id=product_area.id) }}"><i class="ti-eye"></i> View</a>
                                        </td>
                                    </tr>

                                    {% set count = count + 1 %}
                                    {% endfor %}


                                  </tbody>
                                </table>
                              </div>

                            </div>

                          </div>
                        </div>
                    </div>
                    <!-- end row -->


                </div>
                <!-- end container -->

            </div>
      <!-- end content -->
  </div>

  <!-- ============================================================== -->
  <!-- End Right content here -->
  <!-- ============================================================== -->

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header" id="difftype">
              <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
              </div>
              <div class="modal-body">
                  <div class="row text-center">
                      <img src="{{ url_for('static', filename = 'images/delete.png') }}" />
                  </div>
              </div>
              <form action="{{ url_for('productareas.delete')}}" method="post">
                     <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                     <input type="hidden" id="product_area_id" name="product_area_id">
                  <p class="text-center">Are you sure you want to delete this client </p>
                  <p  class="text-center">Initiated for <span id="product_area"></span></p>
                  <div class="modal-footer">
                      <button type="button" class="btn btncan" data-dismiss="modal">DON'T DELETE</button>
                      <button type="submit" class="btn btn-danger">DELETE</button>
                  </div>
              </form>
          </div>
      </div>
  </div>

{% endblock %}

{% block script %}
<script>

  $(function() {
      $('#exampleModal').on("show.bs.modal", function (e) {
          $("#product_area_id").val($(e.relatedTarget).data('id'));
          $("#product_area").text($(e.relatedTarget).data('product_area'));
      });
  });

</script>
{% endblock %}

app/templates/productareas/show.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
{{ super() }}

<div class="content-page">
    <!-- Start content -->
          <div class="content">
                <div class="container">

                  <!-- Page-Title -->
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="page-title-box">
                              <ol class="breadcrumb pull-right">
                                  <li><a href="#">Home</a></li>
                                  <li><a href="#">Product Areas</a></li>
                                  <li class="active">Create New</li>
                              </ol>
                              <h4 class="page-title">Product Area</h4>
                          </div>
                      </div>
                  </div>

                        <div class="row">
                          <div class="col-sm-12">
                            <div class="card-box">
                              <h3>Show Product Area ({{ product_area.id }})</h3>

                              <hr />

                              {{ utils.flashed_messages() }}

                              <div class="container wrapper mb-5">
                                      <div class="container">
                                          <div class="card">
                                              <div class="card-body p-0">
                                                  <table class="table table-hover">
                                                      <tbody>
                                                          <tr style="padding-top:20px;">
                                                              <th scope="row">Product Area</th>
                                                              <td>{{ product_area.product_area }}</td>
                                                          </tr>
                                                          <tr>
                                                              <th scope="row">&nbsp;</th>
                                                              <td>
                                                                  <button class="btn btn-primary generate" onclick="location.href='{{ url_for('productareas.edit', id=product_area.id) }}';">EDIT</button>
                                                                  <button class="btn btn-danger generate" data-toggle="modal" data-target="#exampleModal" data-id="{{product_area.id}}" data-product_area="{{product_area.product_area}}">DELETE</button>
                                                              </td>
                                                          </tr>
                                                      </tbody>
                                                  </table>
                                              </div>

                                          </div>

                                      </div>
                                  </div>



                            </div>
                          </div>

                        </div>
                </div>
        </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="difftype">
            <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <div class="row text-center">
                    <img src="{{ url_for('static', filename = 'images/delete.png') }}" />
                </div>
            </div>
            <form action="{{ url_for('productareas.delete')}}" method="post">
                   <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                   <input type="hidden" id="product_area_id" name="product_area_id">
                <p class="text-center">Are you sure you want to delete this client </p>
                <p  class="text-center">Initiated for <span id="product_area"></span></p>
                <div class="modal-footer">
                    <button type="button" class="btn btncan" data-dismiss="modal">DON'T DELETE</button>
                    <button type="submit" class="btn btn-danger">DELETE</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script>

$(function() {
    $('#exampleModal').on("show.bs.modal", function (e) {
        $("#product_area_id").val($(e.relatedTarget).data('id'));
        $("#product_area").text($(e.relatedTarget).data('product_area'));
    });
});

</script>
{% endblock %}