app/clients/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import Required, Length, Email, Regexp


class ClientForm(Form):

    client_name = StringField('Client Name', validators=[Required()])
    submit = SubmitField('Submit')

app/clients/__init__.py
from flask import Blueprint
clients = Blueprint('clients', __name__)
from  import views

app/clients/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from datetime import datetime
from flask import render_template, session, redirect, url_for, request, \
    flash, abort
from flask_login import login_required, current_user
from . import clients
from forms import ClientForm
from .. import db
from ..models import User, Client, ProductArea, Feature, User, Log


@clients.route('/index')
@login_required
def index():
    """
    List all Clients
    """
    clients = Client.query.all()
    return render_template('clients/index.html', clients=clients)


@clients.route('/new', methods=['GET', 'POST'])
@login_required
def create():
    """
    Add a Client
    """
    form = ClientForm()
    if form.validate_on_submit():
        client = Client(client_name=form.client_name.data)
        try:
            db.session.add(client)
            db.session.commit()
            flash('You have successfully add a Client.')
        except:
            flash('Error: failed to add a client')
        return redirect(url_for('.index'))
    return render_template('clients/create.html', form=form)

@clients.route('/show/<id>')
@login_required
def show(id):
    """
    Show a Client
    """
    client = Client.query.get_or_404(id)
    if client is None:
        abort(404)
    return render_template('clients/show.html', client=client)


@clients.route('/edit/<id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    """
    Edit a Client
    """
    client = Client.query.get_or_404(id)
    form = ClientForm()
    if form.validate_on_submit():
        client.client_name = form.client_name.data
        return redirect(url_for('.show', id=client.id))

    form.client_name.data = client.client_name
    return render_template('clients/edit.html', form=form,
                           client=client)


@clients.route('/delete/', methods=['POST'])
@login_required
def delete():
    """
    Delete a Client
    """
    id = request.form['client_id']
    client = Client.query.get_or_404(id)
    try:
        db.session.delete(client)
        db.session.commit()
        flash('You have successfully deleted the Client.')
    except:
        flash('Error: failed to delete this client')
    return redirect(url_for('.index'))


@clients.context_processor
def inject_logs():
    """
    Make available all logs
    """
    logs = Log.query.all()
    print "logs: ", logs
    return dict(logs=logs)

app/templates/clients/create.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
{{ super() }}

<div class="content-page">
    <!-- Start content -->
          <div class="content">
                <div class="container">

                  <!-- Page-Title -->
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="page-title-box">
                              <ol class="breadcrumb pull-right">
                                  <li><a href="#">Home</a></li>
                                  <li><a href="#">Clients</a></li>
                                  <li class="active">Create Client</li>
                              </ol>
                              <h4 class="page-title">Clients</h4>
                          </div>
                      </div>
                  </div>

                        <div class="row">
                          <div class="col-sm-12">
                            <div class="card-box">
                              <h3>Create Client</h3>

                              <hr />

                            {{ utils.flashed_messages() }}

                            {{ wtf.quick_form(form) }}
                            </div>
                          </div>

                        </div>
                </div>
        </div>
</div>

{% endblock %}

app/templates/clients/edit.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
{{ super() }}

<div class="content-page">
    <!-- Start content -->
          <div class="content">
                <div class="container">

                  <!-- Page-Title -->
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="page-title-box">
                              <ol class="breadcrumb pull-right">
                                  <li><a href="#">Home</a></li>
                                  <li><a href="#">Product Area</a></li>
                                  <li class="active">Edit</li>
                              </ol>
                              <h4 class="page-title">Product Area</h4>
                          </div>
                      </div>
                  </div>

                        <div class="row">
                          <div class="col-sm-12">
                            <div class="card-box">
                              <h3>Edit Product Area ({{client.id}})</h3>

                              <hr />

                            {{ utils.flashed_messages() }}

                            {{ wtf.quick_form(form) }}
                            </div>
                          </div>

                        </div>
                </div>
        </div>
</div>

{% endblock %}

app/templates/clients/index.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}

{% block page_content %}
{{ super() }}

  <!-- ============================================================== -->
  <!-- Start right Content here -->
  <!-- ============================================================== -->

  <div class="content-page">
      <!-- Start content -->
            <div class="content">
                <div class="container">

                    <!-- Page-Title -->
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="page-title-box">

                                <ol class="breadcrumb pull-right">
                                    <li><a href="#">Home</a></li>
                                    <li><a href="#">Client</a></li>
                                    <li class="active">Manage</li>
                                </ol>

                                <h4 class="page-title">Clients</h4>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-12">
                          <div class="card-box">

                            <h3>Manage Clients</h3>

                            <hr />


                            <div class="table-rep-plugin">
                              <div class="table-responsive" data-pattern="priority-columns">

                                  {{ utils.flashed_messages() }}

                                <table id="tech-companies-1" class="table  table-striped">
                                  <thead>
                                    <tr>
                                      <th data-priority="1">SN</th>
                                      <th data-priority="2">Client Name</th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    {% set count = 1 %}
                                    {% for client in clients %}
                                    <tr>
                                        <th><span class="co-name">{{ count }}</span></th>
                                        <td>{{ client.client_name }}</td>
                                        <td>
                                              <a href="#" class="mr-3" data-toggle="modal" data-target="#exampleModal" data-id="{{client.id}}" data-client_name="{{client.client_name}}">
                                                      <i class="md md-delete"></i> Delete
                                              </a>
                                              &nbsp;
                                              <a href="{{ url_for('clients.show', id=client.id) }}"><i class="ti-eye"></i> View</a>
                                        </td>
                                    </tr>
                                    {% set count = count + 1 %}
                                    {% endfor %}


                                  </tbody>
                                </table>
                              </div>

                            </div>

                          </div>
                        </div>
                    </div>
                    <!-- end row -->


                </div>
                <!-- end container -->

            </div>
      <!-- end content -->
  </div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header" id="difftype">
              <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
              </div>
              <div class="modal-body">
                  <div class="row text-center">
                      <img src="{{ url_for('static', filename = 'images/delete.png') }}" />
                  </div>
              </div>
              <form action="{{ url_for('clients.delete')}}" method="post">
                     <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                     <input type="hidden" id="client_id" name="client_id">
                  <p class="text-center">Are you sure you want to delete this client </p>
                  <p  class="text-center">Initiated for <span id="client_name"></span></p>
                  <div class="modal-footer">
                      <button type="button" class="btn btncan" data-dismiss="modal">DON'T DELETE</button>
                      <button type="submit" class="btn btn-danger">DELETE</button>
                  </div>
              </form>
          </div>
      </div>
  </div>

  <!-- ============================================================== -->
  <!-- End Right content here -->
  <!-- ============================================================== -->


{% endblock %}

{% block script %}
<script>

  $(function() {
      $('#exampleModal').on("show.bs.modal", function (e) {
          $("#client_id").val($(e.relatedTarget).data('id'));
          $("#client_name").text($(e.relatedTarget).data('client_name'));
      });
  });

</script>
{% endblock %}

app/templates/clients/show.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
{{ super() }}

<div class="content-page">
    <!-- Start content -->
          <div class="content">
                <div class="container">

                  <!-- Page-Title -->
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="page-title-box">
                              <ol class="breadcrumb pull-right">
                                  <li><a href="#">Home</a></li>
                                  <li><a href="#">Clients</a></li>
                                  <li class="active">Create New</li>
                              </ol>
                              <h4 class="page-title">Clients</h4>
                          </div>
                      </div>
                  </div>

                        <div class="row">
                          <div class="col-sm-12">
                            <div class="card-box">
                              <h3>Show Client ({{ client.id }})</h3>

                              <hr />

                              <div class="container wrapper mb-5">
                                      <div class="container">
                                          <div class="card">
                                              <div class="card-body p-0">

                                                {{ utils.flashed_messages() }}

                                                  <table class="table table-hover">
                                                      <tbody>
                                                          <tr style="padding-top:20px;">
                                                              <th scope="row">Client Name</th>
                                                              <td>{{ client.client_name }}</td>
                                                          </tr>
                                                          <tr>
                                                              <th scope="row">&nbsp;</th>
                                                              <td>
                                                                  <button class="btn btn-primary generate" onclick="location.href='{{ url_for('clients.edit', id=client.id) }}';">EDIT</button>
                                                                  <button class="btn btn-danger generate" data-toggle="modal" data-target="#exampleModal" data-id="{{client.id}}" data-client_name="{{client.client_name}}">DELETE</button>
                                                              </td>
                                                          </tr>
                                                      </tbody>
                                                  </table>
                                              </div>

                                          </div>

                                      </div>
                                  </div>



                            </div>
                          </div>

                        </div>
                </div>
        </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="difftype">
            <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <div class="row text-center">
                    <img src="{{ url_for('static', filename = 'images/delete.png') }}" />
                </div>
            </div>
            <form action="{{ url_for('clients.delete')}}" method="post">
                   <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                   <input type="hidden" id="client_id" name="client_id">
                <p class="text-center">Are you sure you want to delete this client </p>
                <p  class="text-center">Initiated for <span id="client_name"></span></p>
                <div class="modal-footer">
                    <button type="button" class="btn btncan" data-dismiss="modal">DON'T DELETE</button>
                    <button type="submit" class="btn btn-danger">DELETE</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- ============================================================== -->
<!-- End Right content here -->
<!-- ============================================================== -->


{% endblock %}

{% block script %}
<script>

$(function() {
    $('#exampleModal').on("show.bs.modal", function (e) {
        $("#client_id").val($(e.relatedTarget).data('id'));
        $("#client_name").text($(e.relatedTarget).data('client_name'));
    });
});

</script>
{% endblock %}